services:
    # Public

    webserver:
        container_name: ragu-webserver
        restart: unless-stopped
        image : nginx:alpine
        working_dir: /application-ext
        volumes:
            - ./containers/php-fpm-external:/application-ext:ro
            - ./containers/php-fpm-internal:/application-int:ro
            - ./dockerconf/nginx/public.conf:/etc/nginx/conf.d/public.conf:ro
            - ./dockerconf/nginx/internal.conf:/etc/nginx/conf.d/internal.conf:ro
            - ./dockerconf/nginx/empty.conf:/etc/nginx/conf.d/default.conf:ro
            - ./var/logs/nginx:/var/log/nginx
        ports:
            - 20002:80

    #frontend
    #    container_name: ragu-frontend

    php-fpm-external:
        container_name: ragu-php-fpm-external
        restart: unless-stopped
        build:
            context: dockerconf/php-fpm
            dockerfile: Dockerfile_external
        working_dir: /application-ext
        extra_hosts:
            - host.docker.internal:host-gateway
        volumes:
            - ./containers/php-fpm-external:/application-ext
            - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.4/fpm/conf.d/99-overrides.ini
            - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.4/cli/conf.d/99-overrides.ini
            - ./var/logs/php-fpm-external:/application-ext/var/log
        environment:
            - ALLOW_ENV_OVERRIDE=true

    # Internal

    php-fpm-internal:
        container_name: ragu-php-fpm-internal
        restart: unless-stopped
        build:
            context: dockerconf/php-fpm
            dockerfile: Dockerfile_internal
        working_dir: /application-int
        extra_hosts:
            - host.docker.internal:host-gateway
        volumes:
            - ./containers/php-fpm-internal:/application-int
            - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.4/fpm/conf.d/99-overrides.ini
            - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.4/cli/conf.d/99-overrides.ini
            - ./var/logs/php-fpm-internal:/application-int/var/log
        environment:
            - ALLOW_ENV_OVERRIDE=true

volumes:
    ragu-pgdata: