_security_logout:
    resource: security.route_loader.logout
    type: service

jwt_create_token:
    path: /api/auth/login
    controller: App\Controller\AuthController::loginAction
    methods: POST

gesdinet_jwt_refresh_token:
    path:       /api/auth/refresh
    controller: App\Controller\AuthController::refreshAction
