_security_logout:
    resource: security.route_loader.logout
    type: service

jwt_create_token:
    path: /auth/login
    controller: App\Api\Controller\AuthController::loginAction
    methods: POST

gesdinet_jwt_refresh_token:
    path:       /auth/refresh
    controller: App\Api\Controller\AuthController::refreshAction
