gesdinet_jwt_refresh_token:
    refresh_token_class: App\Entity\RefreshToken
    ttl: 604800 # user has to login at least once per week
    ttl_update: true # extend the refresh token validity on each use
